Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: eugene_ecr-demo
      ImageScanningConfiguration:
        ScanOnPush: true
      Tags:
        - Key: Project
          Value: ECR-Lab
